version: "3"
services:
  subtasks-service:
    build: ./
    environment: 
        DB_CONNECTION_URL: mongodb://mongo:27017
        APPLICATION_PORT: 3002
    ports:
      - "3002:3002"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
