version: "3"
services:
  users-service:
    build: ./
    environment: 
        DB_CONNECTION_URL: mongodb://mongo:27017
        APPLICATION_PORT: 4060
    ports:
      - "4060:4060"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
